({
	//name:"index",
	appDir:"./js/",
	dir:"builds",
	baseUrl:"./",
	// out:"main-build.js",
	fileExclusionRegExp:/^(r|build)\.js$/,
	paths:{
		'jquery': './libs/jquery.min',
    'jqueryUI':'./libs/jqueryui/jquery-ui.min',
    'jqueryTime':'./libs/jqueryui/jquery-ui-timepicker-addon.min',
    'jJson': './libs/jquery.json',
    'jForm': './libs/jquery.jqtransform',
    'jtimer': './libs/jquery.timers',
    'domReady':'./libs/domReady',
    'backbone':'./libs/backbone-min',
    '_':'./libs/underscore-min',
    'bootstrap':'./libs/bootstrap',
    "charts":"./libs/echarts.min",
    'zTreeCore':'./libs/jquery.ztree.core-3.5',
    'zTreeExcheck':'./libs/jquery.ztree.excheck-3.5',
    'scrollbar':'./libs/scrollbar/min/perfect-scrollbar.jquery.min',
    'mCustomScrollbar':'./libs/jquery.mCustomScrollbar.concat.min',
    'table':'./libs/jquery.dataTables',
    'fixedColumn':'./libs/dataTables.fixedColumns.min',
    'fixedHeader':'./libs/dataTables.fixedHeader.min',
  	"respond":"./js/respond",
    "router" :"./js/router",
    "api" :"./js/api",
    "main" :"./js/main",
    "login" :"./js/login",
    "ui" :"./js/ui",
    "common" :"./js/common",
    "map" :"./js/map",
    "context" :"./js/context_model",
    "blocks":"./js/blocks",
    "stationsinfoDialog":"./js/dialog-stationsinfo"
	},
	shim:{
      bootstrap:['jquery'],
      table:['jquery'],
      jtimer:['jquery'],
      fixedColumn:['jquery','table'],
      common:['jquery'],
      zTreeCore:['jquery'],
      zTreeExcheck:['zTreeCore'],
      jJson:['jquery'],
      jForm:['jquery'],
      jqueryUI:['jquery'],
      jqueryTime:['jquery','jqueryUI'],
      backbone:['_'],
    	respond:['respond']
  }
})