<?php return array (
'class'=>'CDbConnection',	
'connectionString' => "mysql:host='".$_SERVER['DB_BMS_HOST']."';port=".$_SERVER['DB_BMS_PORT'].";dbname='".$_SERVER['DB_BMS_DATABASE']."'",
	'username' => $_SERVER['DB_BMS_USERNAME'],
	'password' => $_SERVER['DB_BMS_PASSWORD'],
	'charset' => 'utf8',
	'tablePrefix' => 'tb_',
	'emulatePrepare' => true,
	//'enableProfiling' => true,
	//'enableParamLogging'=>true,
	//'queryCacheID'=>'mcache',
	//'queryCachingDuration'=>36000,
	'persistent' => false,
	//'schemaCacheID'=>'mcache',
	//'schemaCachingDuration'=>864000,
);
