<?php return array (
'class'=>'CDbConnection',	
'connectionString' => "mysql:host=127.0.0.1;port=3306;dbname=db_bms_english4",
	'username' => qingda,
	'password' => 123456,
	'charset' => 'utf8',
	'tablePrefix' => 'my_',
	'emulatePrepare' => true,
	//'enableProfiling' => true,
	//'enableParamLogging'=>true,
	//'queryCacheID'=>'mcache',
	//'queryCachingDuration'=>36000,
	'persistent' => false,
	//'schemaCacheID'=>'mcache',
	//'schemaCachingDuration'=>864000,
);
